### ISSUE TITLE
recommended workflow for md:myst notebooks?

### ISSUE THREAD

**Issue by phaustin** [ExecutableBookProject/MyST-NB#106]
Wanted to check my understanding that the best way to compose an md:myst version of a jupyter notebook is to use the cache feature and watchdog/livereload to continually update an html file, so that things like labeled equation numbering is proofed in  a separate browser window side by side, ala vscode's jupyter mode?

**Comment by chrisjsewell** [comment]
Heya, well I guess there is no "recommended" workflow just yet; its all very new! But this certainly seems like an interesting approach to consider, and perhaps something like this could also make its way into https://marketplace.visualstudio.com/items?itemName=ExecutableBookProject.myst-highlight at some point

**Comment by phaustin** [comment]
Once things settle down, is there any technical showstopper to adding markdown-it with the myst extensions to https://github.com/jupyterlab/jupyter-renderers?  Google sent me to https://github.com/jupyterlab/jupyterlab/issues/272 -- it looks like something like this is under consideration?  Nothing urgent here, but as our project moves from summer computer science coop students to the broader community, we'll probably have to focus only on notebook-only rendering, at least for any course material that's going to wind up being executed by students. (or perhaps a postprocesser that produces a markdown-only version of a myst notebook).

**Comment by chrisjsewell** [comment]
> Once things settle down, is there any technical showstopper to adding markdown-it with the myst extensions to https://github.com/jupyterlab/jupyter-renderers?

Well I should think no, given that the extension will now be based around markdown-it #107  😄 

> or perhaps a postprocesser that produces a markdown-only version of a myst notebook

This kind of thing is already semi-achievable with jupytext: https://jupytext.readthedocs.io/en/latest/formats.html#myst-markdown, as in you can pair notebooks to markdown files, and even open the markdown files directly as notebooks

<img width="647" alt="image" src="https://user-images.githubusercontent.com/2997570/77856785-66902080-71f1-11ea-8ea4-a9cfeecb5fb9.png">

**Comment by phaustin** [comment]
yes, I'm all-in on jupytext -- the main decision I'm facing right now (as I get ready to introduce 3 newcomers to myst-nb) is what to do about myst/rst equation labels/cross references that won't render with the standard marked notebook parser.  We've got about 100 notebooks to port from our own hand-coded #id equation and figure labeling, and I think I'm comfortable with commiting to myst for these.  Since everything's parseable we can adapt to whatever works when we start handing these notebooks out to undergrads in September.

**Comment by chrisjsewell** [comment]
Yeh fair, it would definitely be nice to have the consistent render in the notebooks.

Note that in ExecutableBookProject/Myst-Parser#123, for equations, you will now be able to do:

```md
$$
a=1
$$ (id)
```

which should easy portability a little

**Comment by phaustin** [comment]
nice! we'll definitely use that
