### ISSUE TITLE
Errors when re-building docs after deleting a notebook

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#114]
I've found a weird bug that seems to pop up when I build the docs with a notebook in them, then I remove the notebook, then I re-build the docs. I get this error:

```
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/deleted/ipynb-file'
```

So it seems like MyST-NB (or more probably jupyter-cache?) is looking for the notebook even though it is no longer a part of the build.

**Comment by chrisjsewell** [comment]
Are you using the development version? Given that this was ostensibly fixed in 20a249931908dddb3665afd30ac05de022784790

**Comment by choldgraf** [comment]
hmm - will get back to you. It could be that I'm not

**Comment by chrisjsewell** [comment]
it may also be ‘more fixed’ by #107

**Comment by chrisjsewell** [comment]
I think this should be fixed now, can you re-check and close this issue if so ta

**Comment by choldgraf** [comment]
Yep, I think this is now fixed 👍
