### ISSUE TITLE
Text-based notebooks being read as notebooks if jupyter_execute_notebooks=="auto"

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/MyST-NB#130]
This is the offending section of code: https://github.com/ExecutableBookProject/MyST-NB/blob/b64cc307b38c14db469e410434895f13f63773ff/myst_nb/cache.py#L215

We need to check here if needs to be converted first.

Also on an un-related note, when I run into this error, I also noted that if you specify the extension in toctree, e.g.

````
```{toctree}
file.ipynb
```
````

The extension is discarded, so doesn't actually have any bearing on what file will be read (e.g. if you also have a `file.md`). This is currently "expected" behaviour for sphinx (which as I have noted before, wasn't specifically written to handle multiple extension types), but may be confusing/misleading for a user.

**Comment by mmcky** [comment]
thanks for documenting that @chrisjsewell I just ran into the same issue when I tried using `ipynb` extension explicitly.

**Comment by mmcky** [comment]
@AakashGfude is this something you could look into?

**Comment by AakashGfude** [comment]
@mmcky @chrisjsewell thanks for finding this out. I will have a look.
