### ISSUE TITLE
Add Sphinx integration testing

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#15]
Since this is a Sphinx parser, we should add some tests that use Sphinx infrastructure to make sure it behaves as expected. As a start, something like:

* A notebook that has all of the syntax we'd expect to see from users
* A test suite that builds a site from this notebook, and checks the outputs to make sure they behave as expected (or maybe tests the AST?)

Ideally, we could set this up so that, as functionality grows, we can naturally extend the test suite. So I'd like to not do anything *too* bespoke and hacky.

@chrisjsewell or @mmcky or @akhmerov do you have any suggestions or template code you can contribute to start us off with a good way to test Sphinx projects?

**Comment by chrisjsewell** [comment]
Yeh, look at the `test_sphinx` folder (and top-level conftest.py) in the `myst_parser`. It does exactly this, using Sphinx’s pytest fixtures 😁

**Comment by chrisjsewell** [comment]
It also uses `beautifulsoup` and `pytest-regressions` to extract the body of HTML pages and test the against the expected outcome (some things in the footer/header can change dependent on installed package versions etc)

**Comment by choldgraf** [comment]
you are much more disciplined about writing tests than I am...

**Comment by chrisjsewell** [comment]
It’s all about that Test Driven Development life 😂

**Comment by chrisjsewell** [comment]
Most 'lower-level' testing has now been added. But we should add a full sphinx integration test (like in myst-parser)
