### ISSUE TITLE
Release instructions

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#161]
I want to cut a new release for MyST-NB, but I couldn't find the release instructions anywhere here or in myst-parser. If I recall, it's "just" bumping the version, then making a new github release. But I didn't find those instructions anywhere. Do they exist?

**Comment by choldgraf** [comment]
@chrisjsewell if you give me the thumbs up on the steps above, then I'll add the release instructions here, cut a new release, and then will see if tests in https://github.com/ExecutableBookProject/sphinx-book-theme/pull/35 pass and will merge+ cut a release there too

**Comment by chrisjsewell** [comment]
Yep that’s it 👍

**Comment by choldgraf** [comment]
Hmm, I bumped the version in master and made a new release (https://github.com/executablebookproject/myst-nb/releases) but didn't see the action triggered...https://github.com/ExecutableBookProject/MyST-NB/actions

**Comment by choldgraf** [comment]
I wonder if it's because of the changes I made here: https://github.com/ExecutableBookProject/MyST-NB/blob/master/.github/workflows/tests.yml#L3

I'll revert that and see if it changes things

**Comment by chrisjsewell** [comment]
That’s exactly what I was thinking. Either revert or perhaps there is an additional trigger for tags

**Comment by choldgraf** [comment]
yep, that was it, I reverted it...will start working from a fork so I don't keep triggering double-builds
