### ISSUE TITLE
Rename this repository to MystNB

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#29]
I was thinking that `sphinx-notebook` is a really generic name, particularly because there is already both `jupyter-sphinx` and `nbsphinx` (and probably lots of other "notebook" extensions out there).

What if we focused this repository around "Jupyter notebooks with MyST" and re-branded this **SphinxNB**? I even mocked up a (very simple, we'd need to tweak it) logo to see how it feels:

![image](https://user-images.githubusercontent.com/1839645/75096573-cee64500-5555-11ea-9b89-ca32efe43eaf.png)

A few considerations:

* Are we reasonably sure we are sticking with "MyST"? Perhaps in general it could be called "MyST Markdown" as a colloquialism.
* Is it reasonable to say this repository is very MyST-specific? The `ipynb` parser uses MyST to parse, and the text-based representation will also be MySTy...

thoughts? ping @chrisjsewell @jstac @mmcky

**Comment by chrisjsewell** [comment]
Its certainly MyST specific, although obviously the point is that users don't necessarily need to know what MyST is; just that it will convert standard markdown notebooks (with no need for intermediate stages) and that they can 'extend' their markdown with the new syntax if they so choose. I guess it's whether you think it would put off users that don't know what MyST is.

**Comment by chrisjsewell** [comment]
On the other-hand, once MySt is the *de facto* standard for writing text documents, that won't be an issue 😆

**Comment by mmcky** [comment]
I like the ``myst`` name -- I think its memorable and catchy (despite its confusion with Myst the game) :-).

**Comment by jstac** [comment]
`+1` for the name Myst, the repo name change and also the logo, which is actually really good.

(To be clear, when you say **SphinxNB** above, I assume you mean **MystNB** ?)

**Comment by choldgraf** [comment]
Oops - yep I meant **MystNB**...when in doubt, assume the logo is the source of truth 😂

**Comment by choldgraf** [comment]
> despite its confusion with Myst the game

I had the same thought - I think that's a good reason to call it "MyST Markdown" haha

**Comment by choldgraf** [comment]
What do folks prefer:

* `MySTNB`
* `MyST-NB`

?

**Comment by jstac** [comment]
MyST-NB

**Comment by chrisjsewell** [comment]
Yeh `myst-nb` for the package name and `MyST-NB` (or `MyST-Nb`?) when referring to it. I should also change `myst_parser` to `myst=parser` for continuity.

**Comment by choldgraf** [comment]
This is done!
