### ISSUE TITLE
BUG: exception encountered when building a lecture from Quantecon

### ISSUE THREAD

**Issue by AakashGfude** [ExecutableBookProject/MyST-NB#39]
I created a sphinx project with `myst_nb` , `myst_parser` as dependencies. 
When I used the example notebook used in documentation as a source file :- https://github.com/ExecutableBookProject/MyST-NB/blob/master/docs/notebooks.ipynb . It worked fine, for target `html` . But, on using the ipynb file of the numpy lecture from the Quantecon lectures site:- https://python.quantecon.org/_downloads/ipynb/numpy.ipynb, for conversion to `html`, I encountered the following exception:- 

![mistletoe-error](https://user-images.githubusercontent.com/6542997/75739959-7f282a80-5d5a-11ea-99c8-2bbae42214ff.png)

The full traceback is in this log file :- 

[sphinx-err-vmqywraz.log](https://github.com/ExecutableBookProject/MyST-NB/files/4279098/sphinx-err-vmqywraz.log)

**Comment by mmcky** [comment]
thanks @AakashGfude. Just one possible cause. The download notebook from `quantecon` contains markdown -- but it may also contain some `raw` html. Perhaps we should review that notebook for compatibility and then add it to https://github.com/ExecutableBookProject/myst.example-project/ as a `ipynb` source example.

**Comment by mmcky** [comment]
@chrisjsewell will `myst-parser` pass through `html` like other `markdown` parsers?

**Comment by AakashGfude** [comment]
@mmcky correct, the raw html tags could have been one of the causes. This time, I removed the HTML tags, and ran it, but found the same issue.

**Comment by mmcky** [comment]
ok great - thanks for checking @AakashGfude. I guess we will need to see if the markdown is `commonmark` compliant :-)

**Comment by chrisjsewell** [comment]
Yeh it parses HTML. The issue could lie with ExecutableBookProject/MyST-Parser#101, in that myst-nb needs to ensure all lines are terminated by a new line (the error arises because the parser is trying to access a ‘next’ line that doesn’t exist). I believe @choldgraf has just added a fix for this on myst-nb

**Comment by chrisjsewell** [comment]
Yeh give it a try now that #38 is merged

**Comment by AakashGfude** [comment]
@chrisjsewell thanks, it is working now.
