### ISSUE TITLE
IPYNB parsing: auto-register scrapbook scraps somehow

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#4]
An idea I just had when thinking about how we can reference content from one notebook to another - what if as a part of the Sphinx parser we automatically generated docutils targets from any scraps that are in a notebook during the parsing process. That way references to those targets could already exist and users could reference them with a role, similar to what we do with `:ref:`. I'm imagining something like:

## In a notebook

Somebody writes an analysis that generates a plot they'd like to include elsewhere in their docs. They run `scrapbook.glue('myplot')`

## In a MyST document

Somebody wants to include that "scrap" from the notebook. They only need to do something like

```
{scrap}`myplot`
```
and Sphinx just looks up `myplot` against a list of scraps that it has found across any parsed notebook.

**Comment by choldgraf** [comment]
@chrisjsewell I've been thinking about this a bit more - do you imagine that this should be in `jupyter-cache`? I think `myst-nb` would need to have the logic if "given a notebook path, and given a role like `{scrap}` (maybe `{paste}`?), return the value according to the `{paste}` key that was given". But the question is: what's the thing that does the glueing in the first place?

**Comment by chrisjsewell** [comment]
You could do something like process the stored outputs for these stored scraps, at commit time, then store them in the DB commit record, for fast lookup. **However**, a complication is that the cache can store multiple versions of a notebook which would lead to key clashes, and the cached notebooks don't necessarily relate to what notebooks are being used in the sphinx build.

Therefore, I think this may be better handled in the MyST-NB parser: 

- When we write the notebook here: https://github.com/ExecutableBookProject/MyST-NB/blob/bde00319a669e51bdfa24f30411f1d4052358b25/myst_nb/parser.py#L133 also find and add these scaps to a 'database' file:
  - JSON would be simplest, as long as there is no issues with read/write access that is better handled by SQL).
  - before adding we would wipe any previously associated with that docname
  - We would also need to check and report on any key clashes

- Then, when we want to find these scraps (probably in a transform), query this DB file for the required outputs.

**Comment by choldgraf** [comment]
so do you imagine something like:

```
from jupyter_cache import cache
a = 2
cache("var_a", a)

ax = plt.plot([2], [3])
cache("cool_plot", ax.figure)
```

and it'd store the mimebundle outputs in the notebook metdata (maybe `jupyter-cache: {}`)

For a simplest implementation, we could do something like:

1. At parse time, check the `ipynb` file for anything in `jupyter-cache:` and add it to a dictionary that spans all notebooks. Something like
  
  ```
  notebooks_cache = {
    "path_ntbk1": {"key": "val"},
    "path_ntbk2": {"key": "val"}
  }
  ```
2. Expose a role like `` The value of my variable is {paste}`path_ntbk1:key` `` that will search for that notebook and retrieve the key. And a shorthand `` {paste}`key` `` that will search all the notebooks and return the proper value *only if there is only one instance of the key*.
3. Expose a directive like:

   ````
   ```{paste} path_to_notebook:key
   ```
   ````

   And it inserts a `CellNode` and `CellOutputBundleNode` at this location in the doctree, with the output bundle coming from that key.

Over time, this could be modified to use a smarter cacheing mechanism than a dictionary, but I'm just imagining a quick working prototype. WDYT?

**Comment by chrisjsewell** [comment]
> and it'd store the mimebundle outputs in the notebook metdata

It would probably just store it in the outputs, but with a prefix on the mimetype, so that its ignored by general renderers (as scrapbook does)

**Comment by choldgraf** [comment]
Ah yeah, and then as we loop through the cells, check the outputs for a mimetype meant for caching and then store it?

**Comment by chrisjsewell** [comment]
> For a simplest implementation, we could do something like:

But yeh thats the general idea
