### ISSUE TITLE
Add the ability to execute notebooks

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#48]
In addition to full jupyter-cache support, we should also probably allow for lightweight execution of notebooks at build time, so that users don't have to embed outputs with their notebooks if they wish for them to be in the docs.

We could do this with nbclient, I think the question is how to handle things like "known exceptions" etc.

A simple rubric to follow would be what nbsphinx does, and decide whether to execute a notebook top-to-bottom if it has no outputs in any cells.

**Comment by chrisjsewell** [comment]
> We could do this with nbclient, I think the question is how to handle things like "known exceptions" etc.

Just to note, we should endeavour to make sure that the execution logic is consistent over `jupyter-cache`, `jupyter-sphinx` and `myst-nb`, e.g. how known execptions are handled.

**Comment by chrisjsewell** [comment]
I believe this was handled in #55
