### ISSUE TITLE
Update `myst-parser` version

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/MyST-NB#49]
This: https://github.com/ExecutableBookProject/MyST-NB/blob/51e97a23ed5232d558b16042ab65b2b667a33235/myst_nb/parser.py#L78

will now be:

```python
        document = Document.read(cell["source"], front_matter=False)
```

When you update the dependency to `myst-parser~=0.4.1`. See: https://github.com/ExecutableBookProject/MyST-Parser/blob/786d99bba3c81fe86ca81ddeddb721b4a1fc3473/myst_parser/block_tokens.py#L44

Nothing else should have changed.

**Comment by choldgraf** [comment]
This is now implemented, right?
