### ISSUE TITLE
Explore using jupyter-sphinx

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#5]
I was looking into sphinx-jupyter and I think it might be useful as a part of our build chain. It specifies directives for parsing and running cells as a doctree transformation, and I think expects people will directly use jupyter directives as opposed to using jupyter notebooks as inputs.

Three ways I could imagine using it (off top of my head) 

* if we end up doing execution within sphinx we could try utilizing this directly. In this case we might want to add some caching somehow 
* if we keep execution pre-sphinx we could try seeing if jupyter-sphinx would be friendly to allowing a read-only ipynb parser that uses the myst markdown parser under the hood.
* if they aren't OK with that, we can take heavy inspiration or reuse components from jupyter sphinx in how we render cells, outputs, etc. 

I wonder if @akhmerov has thoughts on that!

**Comment by akhmerov** [comment]
Sorry, do you mind editing the issue title and description `s/sphinx-jupyter/jupyter-sphinx/g`? Irks me a bit each time I see.
