### ISSUE TITLE
Improve integration with sphinx-copybutton

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/MyST-NB#65]
The copy button is inset for code cells:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/2997570/76571671-eb6c0200-64af-11ea-8ce3-3e8d9e931947.png">

Also see: https://3-241082514-gh.circle-artifacts.com/0/html/using/api.html

**Comment by choldgraf** [comment]
Good catch - I think we could get around this by making sure that the inner container doesn't have the padding on the right:

![image](https://user-images.githubusercontent.com/1839645/76572961-bd1f0000-6478-11ea-8759-e76f7942c82d.png)

The copy button is correctly being placed at the top-right of the container (see the output cells), but the top-right of the container is in a bit too much
