### ISSUE TITLE
Fix line number / cell index reporting

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/MyST-NB#71]
So that sphinx will report errors/warnings referring to correct place in the notebook

**Comment by choldgraf** [comment]
Could we pass in the cell number into the state machine somehow? I feel like cell numbers are more helpful to report here than line numbers

**Comment by chrisjsewell** [comment]
Well ideally you'd report both. Its just thinking of a way to do this that ideally still keeps `myst-parser` (where some of this logic would need to be added) agnostic to notebooks.

Note the cell index is now stored in the markdown AST: https://github.com/ExecutableBookProject/MyST-NB/blob/4c3f36b884086878dc0af5dfcfd735b98ebbbacf/myst_nb/parser.py#L94,
its just then how to get this into the docutils AST and reported by the docutils reporter.
