### ISSUE TITLE
Use `glue` as a placeholder for `glu:any`?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-NB#78]
As I was typing the docs in #77 , I found it a bit tedious to keep typing `glu:any`. I wonder if we could use the full word `glue` for this particular use-case (and keep `glu:any` for more explicit usage).

So, for any output-specific command, use `glu:text`, `glu:figure`, etc. For generic outputs, use `glue` or `glu:any`.

What do folks think?

**Comment by choldgraf** [comment]
After doing some demos of this, I wonder again if we could use simply `{glue}` instead of requiring `{glue:}` to be short-hand for `{glue:any}`. The reason I think it might be possible is because I noticed that Sphinx has both a Math domain (https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#the-math-domain) as well as a `{math}` directive: https://www.sphinx-doc.org/en/latest/usage/restructuredtext/directives.html#directive-math

So I wonder, could we have a `{glue}` directive and role that just short-cuts to the one called from within the `{glue}` domain? Apologies if this still isn't possible, I seem to remember @chrisjsewell saying it wasn't, but I wanted to double check because I do think users will forget to type the extra `:`.

**Comment by chrisjsewell** [comment]
Err I guess it might be technically possible. On the flip side, you could always rename the python function to `glu` rather than `glue`

**Comment by chrisjsewell** [comment]
Moving discussion to #110
