### ISSUE TITLE
Ensure Math Is Parsed/Rendered Consistently

### ISSUE THREAD

**Issue by phaustin** [ExecutableBookProject/MyST-NB#99]
The top two equations [here](https://github.com/phaustin/MyST-NB/blob/tex_format/docs/examples/austin_issue/lab8/lab8_snip.ipynb) succeed with nbsphinx but not myst_nb.    Reference PR #98

**Comment by chrisjsewell** [comment]
FYI @phaustin this shoud hopefully be fixed in ExecutableBookProject/MyST-Parser#123

**Comment by phaustin** [comment]
Hi @chrisjsewell -- trying this, but I'm getting the following error when I try to do `make html` in docs:

first I do 
```
pip install myst-nb==0.6.0a1
pip install myst-parser[sphinx]==0.8.0a3
```
then checkout current tip

```
% git log -4
commit f07f2253297df60a33fb23b32c71af0b2c819016 (HEAD -> master, origin/master, origin/HEAD)
Author: AakashGC <aakashguptachoudhury@gmail.com>
Date:   Wed Apr 1 06:35:29 2020 +1100

    Documentation for unit testing (#112)
```

```
% make html
Running Sphinx v2.4.4
WARNING: while setting up extension jupyter_sphinx: extension 'jupyter_sphinx' has no setup() function; is it really a Sphinx extension module?
Adding copy buttons to code blocks...
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 13 source files that are out of date
updating environment: Executing: /Users/phil/repos/MyST-NB/docs/use/interactive.ipynb
Execution Succeeded: /Users/phil/repos/MyST-NB/docs/use/interactive.ipynb
Executing: /Users/phil/repos/MyST-NB/docs/use/glue.ipynb
Execution Succeeded: /Users/phil/repos/MyST-NB/docs/use/glue.ipynb
Executing: /Users/phil/repos/MyST-NB/docs/use/orphaned_nb.ipynb
Execution Succeeded: /Users/phil/repos/MyST-NB/docs/use/orphaned_nb.ipynb
Executing: /Users/phil/repos/MyST-NB/docs/use/hiding.ipynb
Execution Succeeded: /Users/phil/repos/MyST-NB/docs/use/hiding.ipynb
Executing: /Users/phil/repos/MyST-NB/docs/use/basic.ipynb
Execution Succeeded: /Users/phil/repos/MyST-NB/docs/use/basic.ipynb
[new config] 13 added, 13 changed, 0 removed
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:26: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:37: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:41: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:49: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:64: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:71: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:97: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:113: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:121: WARNING: Unknown directive type 'jupyter-execute'
/Users/phil/repos/MyST-NB/docs/examples/jupyter_sphinx.md:128: WARNING: Unknown directive type 'jupyter-execute'

Exception occurred:
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/myst_parser/docutils_renderer.py", line 94, in __init__
    self.reporter = self.document.reporter  # type: Reporter
AttributeError: 'MarkdownIt' object has no attribute 'reporter'
The full traceback has been saved in /var/folders/_k/0f_hlw7x2hq4vtcq0h8bvsm40000gr/T/sphinx-err-8510nzpt.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```
full log:
```
# Sphinx version: 2.4.4
# Python version: 3.7.6 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.1
# Last messages:
#   Executing: /Users/phil/repos/MyST-NB/docs/use/basic.ipynb
#   Execution Succeeded: /Users/phil/repos/MyST-NB/docs/use/basic.ipynb
#   [new config]
#   13 added, 13 changed, 0 removed
#   reading sources... [  7%] develop/contributing
#   reading sources... [ 15%] develop/index
#   reading sources... [ 23%] examples/index
#   reading sources... [ 30%] examples/jupyter_sphinx
#   reading sources... [ 38%] index
#   reading sources... [ 46%] use/basic
# Loaded extensions:
#   sphinx.ext.mathjax (2.4.4) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/alabaster/__init__.py
#   myst_parser (0.7.1) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/myst_parser/__init__.py
#   sphinx_togglebutton (0.0.2) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx_togglebutton/__init__.py
#   jupyter_sphinx (unknown version) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/jupyter_sphinx/__init__.py
#   myst_nb (0.6.0a1) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/myst_nb/__init__.py
#   sphinx_copybutton (0.2.10) from /Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx_copybutton/__init__.py
#   pydata_sphinx_theme (unknown version) from /Users/phil/repos/pydata-sphinx-theme/pydata_sphinx_theme/__init__.py
Traceback (most recent call last):
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/application.py", line 349, in build
    self.builder.build_update()
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 299, in build_update
    len(to_build))
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/io.py", line 316, in read_doc
    pub.publish()
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/docutils/core.py", line 218, in publish
    self.settings)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/sphinx/io.py", line 130, in read
    self.parse()
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/myst_nb/parser.py", line 58, in parse
    md_parser, env, tokens = nb_to_tokens(ntbk)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/myst_nb/parser.py", line 78, in nb_to_tokens
    md = default_parser().disable("front_matter", ignoreInvalid=True)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/myst_parser/main.py", line 32, in default_parser
    MarkdownIt("commonmark", renderer_cls=renderer_cls)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/markdown_it/main.py", line 37, in __init__
    self.renderer = renderer_cls(self)
  File "/Users/phil/a50037/envs/cdp/lib/python3.7/site-packages/myst_parser/docutils_renderer.py", line 94, in __init__
    self.reporter = self.document.reporter  # type: Reporter
AttributeError: 'MarkdownIt' object has no attribute 'reporter'
```

**Comment by chrisjsewell** [comment]
Firstly, you only need to do `pip install myst-nb==0.6.0a1` (actually now `0.6.0a2`), that will also install `myst-parser`.
Secondly, this release isn't from `origin/master`, it's from the `markdown-it` branch. From the log above you can see that its loading extension `myst_parser (0.7.1)`, which is obviously not right 😁

**Comment by phaustin** [comment]
oops -- ok, now building with https://github.com/phaustin/MyST-NB/tree/tex_format/docs/examples/austin_issue  

which produces https://phaustin.github.io/MyST-NB/

1) Things look good with $$ delimiters:  https://phaustin.github.io/MyST-NB/lab8/lab8_dollar_delim.html

2) But parsing has problems with a single multiline equation with latex equation delimters:
https://phaustin.github.io/MyST-NB/lab8/lab8_env_delim.html  

3) (also note that the half-space `\,` isn't working in this case for the continuity equations)

4) When I do mulitple sphinx builds, I'm getting recursive copies of a folder called `jupyter_execute` which contains the py and ipynb files and another copy of jupyter_execute -- is an existence check missing for that folder?

**Comment by chrisjsewell** [comment]
> But parsing has problems with a single multiline equation

I might be one step ahead of you here lol. There is now the `myst-nb==0.6.0` *non-alpha* release on master, and the final fix here was to allow new lines in inline math: ExecutableBookProject/myst-parser.example-project#16

**Comment by phaustin** [comment]
I think I'm catching that?  https://github.com/phaustin/MyST-NB/blob/tex_format/docs/examples/austin_issue/environment.yml

**Comment by chrisjsewell** [comment]
> I think I'm catching that? https://github.com/phaustin/MyST-NB/blob/tex_format/docs/examples/austin_issue/environment.yml

Have you re-installed since earlier today though? For the first two, in the first instance, what I need are additional tests to add to https://github.com/ExecutableBookProject/markdown-it-py/blob/master/tests/test_math/fixtures_dollar.md, of the form:

```
Test Title:
.
markdown text
.
expected HTML text
.
```

**Comment by chrisjsewell** [comment]
> When I do mulitple sphinx builds, I'm getting recursive copies of a folder called jupyter_execute which contains the py and ipynb files and another copy of jupyter_execute -- is an existence check missing for that folder?

As in the folder looks like?

```
_build/
  jupyter_execute/
    nb.ipynb
    nb.py
    jupyter_execute/
      nb.ipynb
      nb.py
      jupyter_execute/
     ...
```

**Comment by phaustin** [comment]
re: recursion -- that's right

**Comment by phaustin** [comment]
```
~/repos/MyST-NB/docs/examples/austin_issue myst [tex_format] phil@rail16
% ls -lR jupyter_execute | grep jupyter
drwxr-xr-x  4 phil  staff  128 Apr  1 08:53 jupyter_execute
jupyter_execute/jupyter_execute:
drwxr-xr-x  3 phil  staff   96 Apr  1 08:53 jupyter_execute
jupyter_execute/jupyter_execute/jupyter_execute:
jupyter_execute/jupyter_execute/jupyter_execute/lab8:
jupyter_execute/jupyter_execute/lab8:
jupyter_execute/lab8:
```

**Comment by chrisjsewell** [comment]
weird! I haven't encountered that, will probably test this after merging #116 (in the next day or so), which is the last major-ish update planned in the near future.

the path is "selected" here: https://github.com/ExecutableBookProject/MyST-NB/blob/18288f6290ebfea648b0a7e00bd0bf3c8a82fc3b/myst_nb/parser.py#L298

If your running in dev mode, you could try adding some print commands around here to see whats going on

**Comment by phaustin** [comment]
will do

**Comment by phaustin** [comment]
Looking over the markdown-it-test, I think my issue is just misunderstanding the current requirements for myst syntax.  That is, I was assuming that the following legal nbconvert/nbsphinx math:

```
\begin{equation}
\frac {\partial u}{\partial x} + \frac{\partial v}{\partial y} = - \, \frac{\partial w}{\partial z}
\end{equation}
```
would work with myst, but it looks like extra $$ delimiters are also mandatory,  i.e.

```
$$
\begin{equation}
\frac {\partial u}{\partial x} + \frac{\partial v}{\partial y} = - \, \frac{\partial w}{\partial z}
\end{equation}
$$
```
works as expected.

**Comment by chrisjsewell** [comment]
Yes absolutely; this is the general CommonMark implementation. Note that, since markdown-it is pluggable, you could always add extensions to do these kind of things; at the expense of decreased parsing speed, increasing complexity etc

**Comment by phaustin** [comment]
yes, I think it would be good to call that pretty prominently in the documentation, since everybody with an nbsphinx notebook stack is going to need to do a filtering pass to add dollar signs.

**Comment by chrisjsewell** [comment]
> > When I do mulitple sphinx builds, I'm getting recursive copies of a folder called jupyter_execute which contains the py and ipynb files and another copy of jupyter_execute -- is an existence check missing for that folder?
> 
> As in the folder looks like?
> 
> ```
> _build/
>   jupyter_execute/
>     nb.ipynb
>     nb.py
>     jupyter_execute/
>       nb.ipynb
>       nb.py
>       jupyter_execute/
>       ...
> ```

@choldgraf in your testing, make sure to look out for this

**Comment by choldgraf** [comment]
I haven't run into this specifically before, but have found some weirdness with the output_folder so I'll keep an eye out

**Comment by phaustin** [comment]
@chrisjsewell and @choldgraf -- good news on this compatibility issue, I think.  The difference between the standard notebook html and the current myst html isn't due to the parser -- it's the mathjax configuration in the header.  Here's current jupyter:  

https://github.com/phaustin/MyST-NB/blob/tex_format/docs/examples/austin_issue/lab8/lab8_nbconvert.html#L13032-L13037

the current MyST-NB template doesn't set the configuration parameters.  If we want compatibility with current notebooks we just need a way to set processEnvironments: true  as an option or the default.

**Comment by chrisjsewell** [comment]
cheers @phaustin, thats one for you @choldgraf

**Comment by choldgraf** [comment]
Good catch - are we +1 on supporting markdown flavors where Jupyter technically departs from CommonMark markdown? I don't think that supporting latex-style math delimiters is in the CM spec, so this should be an intentional decision that we also note in the docs. I think I'm +1 on it, just checking with y'all...

**Comment by phaustin** [comment]
It looks like since about 2015 or so Jupyter has been recommending the $$-free approach -- if you scoll down to the bottom [here](https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Typesetting%20Equations.ipynb) you'll see they consider $$ to be legacy-only.  So I don't think it necessarily needs to be the default, but it would be important to have a way to set  it so new math-heavy users with their own Jupyter notebooks can start using myst without having to convert a ton of legacy ipynb files.  Also, even if we are lucky enough to get markdown-it accepted as the new default jupyer parser, I'm presuming it's unlikely the backward compatibility break would be worth it?

(and for us it would be  helpful if there was a general way to configure the header template, since it's going to be quite a bit more complicated to specify things when mathjax is in turn nested inside pagedjs. Specifically, we're going to need to modify the base pydata-sphinx-theme mathjax.py [to something like this:](https://github.com/eoas-ubc/paged_trio/blob/master/pagelib/project_templates/nbconvert/templates/printit/index.html.j2#L17-L52)

**Comment by chrisjsewell** [comment]
I certainly take your point about legacy support. It's a bit strange though that they consider $ delimiters legacy, when the actual mathjax documentation states

> By default, MathJax will also render all environments outside of delimiters, e.g., \begin{matrix}...\end{matrix} would be processed even if it is not in math mode delimiters, though you are encouraged to use proper delimiters for these cases to make your files more compatible with actual LaTeX. 

(https://docs.mathjax.org/en/latest/input/tex/delimiters.html)

I certainly feel that $ delimiters are the accepted way of doing this (at least outside Jupyter):

- https://talk.commonmark.org/t/mathematics-extension/457/31
- https://talk.commonmark.org/t/mathjax-extension-for-latex-equations/698/17

But as mentioned, parsing of latex math environments can just be added as an (optional) markdown-it(-py) extension.

**Comment by choldgraf** [comment]
OK cool, I'll add in the default jupyter notebook mathjax config into the header for jupyter book pages.

Also just an FYI, I don't think that Jupyter has an "official" stance on dollar signs in mathjax. I think this link is the closest thing to the "official" jupyter markdown standard: https://nbformat.readthedocs.io/en/latest/markup.html#what-flavor-of-markdown-does-the-notebook-format-support

**Comment by phaustin** [comment]
yes, but note in that link they set `processEnvironments: true`, which means, don't require the $$ -- treat these latex environments:  http://docs.mathjax.org/en/latest/input/tex/macros/#environments  in the same way that markdown treats raw html -- just pass it through to let the browser javascript deal with it.

I think the $$ format should be given the highest profile, and that it will eventually win out because it permits reliable equation cross-referencing.  The myst version of the docs should flip the emphasis of the  jupyter examples, using $$ for everything but mentioning at the end that raw latex is also acceptible.

**Comment by phaustin** [comment]
Another complication I can see coming is with the latex writer -- if there's a mixture of the new equation number labeling (which turns on numbers only for labeled equations) and raw unstared environments, 
that are passed through as straigh latex, then
```
\begin{align}
\end{align}
```
would would be numbered in latex, but  the unlabled:

```
$$
\begin{align}
\end{align}
$$
```
presumably wouldn't -- something to call out in the documentation, I guess.

**Comment by choldgraf** [comment]
agreed about the emphasis being on `$$`. I think in general "explicit is better than implicit" and I like asking users to explicitly say "this block is a math block" rather than inferring it from some common latex terms

**Comment by phaustin** [comment]
Looks like we can ensure  equation number compatibility between html and latex versions of myst documents by making [mathtools](https://ctan.org/pkg/mathtools) the default math package instead of amsmath, and turning on its option to only number referenced equations

**Comment by choldgraf** [comment]
Hmm - that one sounds like a discussion worth having. Want to create a new issue for it so that we can iterate there? I am not sure the implications of mathtools vs. amsmath...

**Comment by phaustin** [comment]
will do

**Comment by chrisjsewell** [comment]
Before we get on to all these things bout mathjax and mathtools, I think its important to baseline what the actual parsing/rendering process is for markdown -> sphinx, as it seems all this stuff is making it a lot more complicated than it maybe needs to be!

This is how it currently works for `$` delimited math, and how ideally it should also work for identifying latex math environments directly

1. In the `markdown-it-py` `texmath` extension we identify dollar delimited inlines and blocks: https://github.com/ExecutableBookProject/markdown-it-py/blob/2a01f4ea865f885e7e34c2a861020e884b9bb14f/tests/test_math/test_math.py#L43

e.g.

```
$$
a=1
c
b=2$$  (abc)
```

goes to a parsed token:

```python
  {
        "type": "math_block_eqno",
        "tag": "math",
        "nesting": 0,
        "attrs": None,
        "map": None,
        "level": 0,
        "children": None,
        "content": "\\na=1\\n\\nc\\nb=2",
        "markup": "$$",
        "info": "abc",
        "meta": {},
        "block": True,
        "hidden": False,
    }
```

2. In `myst_parser.DocutilsRenderer` we take that token and convert it to a `docutils.nodes.math_block` (plus a target if it has a label): https://github.com/ExecutableBookProject/MyST-Parser/blob/8e505e4c569692df2a6367f7072ba526d30d003c/myst_parser/sphinx_renderer.py#L49

```xml
<document source="docname">
    <target ids="equation-abc">
    <math_block docname="mock_docname" label="abc" nowrap="False" number="1" xml:space="preserve">
        a=1
        c
        b=2
```

Note at the moment, the `nowrap` option of https://www.sphinx-doc.org/en/1.0/ext/math.html, is always set to False, but it may be the case that we want to do additional check here whether the math is enclosed in latex tags of not and set `nowrap` accordingly.

But now sphinx knows that this is math and should act accordingly.

What I would like to understand then is where mathjax enters the equation (pun intended!).
Do we actually need #121, or can we handle it in a more output agnostic way, as above?

**Comment by choldgraf** [comment]
@chrisjsewell I think that's worth discussion as well...just seems like it'd be better in separate / modular issues instead of this mega issue with a "tex is broken" title.

To your point about output-agnosticity, I am definitely +1 on that...we can treat #121 as a stop-gap just to encourage consistency with the notebook UI for now

**Comment by chrisjsewell** [comment]
> instead of this mega issue with a "tex is broken" title.

Well you can always just change the name lol 😜

**Comment by choldgraf** [comment]
If you wanna leave it in this issue that's fine, but in my experience having multiple different conversations in the same github issues makes it harder to reference that issue later on, harder for newcomers to join discussion, and results in issue pages that take like 10 seconds to load in their entirety...

**Comment by chrisjsewell** [comment]
I'm easy either way; as long as we have a reference of the previous discussion

**Comment by choldgraf** [comment]
we can keep it here if we think it'll be a relatively tightly-scoped conversation. Alternatively we can keep lobbying GitHub to have an option for "latest comments at the top" UI 😄

**Comment by chrisjsewell** [comment]
good point, that would be helpful!

**Comment by phaustin** [comment]
I'd vote for a new issue, since the stuff about recursion, etc. is noise at this point.  Making a pull request that adds the jupyter docs math notebook, since I think it would be good to have specific behavior to talk about

**Comment by mmcky** [comment]
I would vote for a new issue -- I also think a `LaTeX` reference in the docs would be great to start documenting default packages and settings. It would be a nice resources to have later down the track to track options that will need pass through support for both `html` and `latex`

**Comment by phaustin** [comment]
Discussion migrated to #126
